""" BTC """
MINIMUM_BUY_SELL = .001
CURRENT_HIGHEST_USD = 42000


""" Coinbase """
PRETEND_FEE_RATE = .0052  # .52%. Add padding
TAKER_FEE_RATE = .005
MAKER_FEE_RATE = .005

""" Margins """
SELL_MIN = .002

""" Settings """
TRADE_LOCAL_ONLY = True
EMERGENCY_SELL_SAMPLE = 10
